### PR TITLE
Update the patches after vp9 encoder merged.

### PR DESCRIPTION
**Pull request by HeJunyan**

### CODE REVIEW

**Comment by uartie** [comment]
For the submodule commit, please set message according to https://github.com/intel/cartwheel-gstreamer?tab=readme-ov-file#administrators

**Comment by HeJunyan** [comment]
> For the submodule commit, please set message according to https://github.com/intel/cartwheel-gstreamer?tab=readme-ov-file#administrators

The problem is that I really followed the "administrators" manner.

**Comment by uartie** [comment]
> > For the submodule commit, please set message according to https://github.com/intel/cartwheel-gstreamer?tab=readme-ov-file#administrators
> 
> The problem is that I really followed the "administrators" manner.

The commit message says "modified content".  You'll need to make the commit "right after" you update the module and before applying any patches.  The commit message should look similar to https://github.com/intel/cartwheel-gstreamer/commit/5e8332c5767c66a95466464d325e4c6d3b2fed89

**Comment by uartie** [comment]
Also, maybe try to ensure your "git" installation is up-to-date.  I have 2.42.0 and it works as expected.

**Comment by uartie** [comment]
...and `git status` should say the "nothing to commit, working tree clean" right before running the "administrator" steps

**Comment by HeJunyan** [comment]
Oh, I think my problem is that, every time, I will have a diff:

[00:40:07 laptop cartwheel-gstreamer] *dev_main$ git status
On branch dev_main
Your branch is up to date with 'upstream/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   gstreamer (new commits, modified content)

no changes added to commit (use "git add" and/or "git commit -a")


It always has a local change in submodule of gstreamer, and no matter how "git reset", it can not be reset.

**Comment by uartie** [comment]
> Oh, I think my problem is that, every time, I will have a diff:
> 
> [00:40:07 laptop cartwheel-gstreamer] *dev_main$ git status On branch dev_main Your branch is up to date with 'upstream/main'.
> 
> Changes not staged for commit: (use "git add ..." to update what will be committed) (use "git restore ..." to discard changes in working directory) (commit or discard the untracked or modified content in submodules) modified: gstreamer (new commits, modified content)
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> 
> It always has a local change in submodule of gstreamer, and no matter how "git reset", it can not be reset.

Try `git submodule update` to reset your local submodule to a clean state.  If that does not work, then in the submodule directory you may need to stash your changes first.

**Pull request merged**
