### PR TITLE
Update submodule and remove gst-libav patches

### PR DESCRIPTION
**Pull request by uartie**
The gst-libav avvideocompare MR is merged upstream as commit 649d59b88b4e.  Thus, remove associated
cartwheel patches.

Submodule gstreamer a79774be7442..649d59b88b4e

### CODE REVIEW

**Comment by uartie** [comment]
The failure is in gst-vaapi HEVCe 10bit on CML only.  Unfortunately, we don't continuously test gst-vaapi on cartwheel (post-merge)... only during PR pre-check.  I will submit PR without functional change to see if this is caused by new upstream version of avvideocompare or something else.

**Review by xhaihao — APPROVED** [review]
LGTM

**Comment by uartie** [comment]
> LGTM

Still debugging regression

**Comment by xhaihao** [comment]
@uartie The regression might be caused by media-driver because it is on CML only.

**Comment by uartie** [comment]
> @uartie The regression might be caused by media-driver because it is on CML only.

That was my first guess.  But I did a sanity check with #61 (non-functional change) and it passed all checks.  So something about the differences in upstream MR changes vs. original cartwheel patches seems to have caused this.

**Comment by uartie** [comment]
> > @uartie The regression might be caused by media-driver because it is on CML only.
> 
> That was my first guess. But I did a sanity check with #61 (non-functional change) and it passed all checks. So something about the differences in upstream MR changes vs. original cartwheel patches seems to have caused this.

That is, the upstream avvideocompare has diverged from the cartwheel version after addressing the upstream reviews 😢

**Comment by uartie** [comment]
Video meta in allocation query was removed and caused the regression.  Adding patch to this PR to fix it.  I will send the patch to upstream tomorrow.

**Comment by uartie** [comment]
FYI, failure signature was:
```
[2023-05-05 02:02:55.077222] DEBUG: slash: CALL: gst-launch-1.0 -vf filesrc location=/opt/media/test-results/vaapi-fits/iHD/78293d5e-eae8-11ed-bba1-0242ac120002_0/_0.test.gst-vaapi.encode.10bit.hevc/cqp/78293d5e-eae8-11ed-bba1-0242ac120002_0_932_1.h265 ! h265parse ! vaapih265dec ! videoconvert chroma-mode=none dither=0 ! video/x-raw,format=P010_10LE ! avvideocompare method=psnr stats-file=/opt/media/test-results/vaapi-fits/iHD/78293d5e-eae8-11ed-bba1-0242ac120002_0/_0.test.gst-vaapi.encode.10bit.hevc/cqp/78293d5e-eae8-11ed-bba1-0242ac120002_0_932_1.psnr name=cmp ! fakesink filesrc location=/opt/assets/otc-media/bat/yuv/1080P_1920x1080.P010 num-buffers=150 ! rawvideoparse format=p010-10le width=1920 height=1080 framerate=25 ! videoconvert chroma-mode=none dither=0 ! video/x-raw,format=P010_10LE ! cmp. (pid: 42937)
[2023-05-05 02:02:55.092766] DEBUG: slash: Setting pipeline to PAUSED ...
[2023-05-05 02:02:55.094467] DEBUG: slash: Pipeline is PREROLLING ...
[2023-05-05 02:02:55.094564] DEBUG: slash: Got context from element 'vaapidecode_h265-0': gst.gl.GLDisplay=context, gst.gl.GLDisplay=(GstGLDisplay)"\(GstGLDisplayEGL\)\ gldisplayegl0";
[2023-05-05 02:02:55.094612] DEBUG: slash: Got context from element 'vaapidecode_h265-0': gst.vaapi.Display=context, gst.vaapi.Display=(GstVaapiDisplay)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1", gst.vaapi.Display.GObject=(GstObject)"\(GstVaapiDisplayDRM\)\ vaapidisplaydrm1";
[2023-05-05 02:02:55.095473] DEBUG: slash: Redistribute latency...
[2023-05-05 02:02:55.095775] DEBUG: slash: /GstPipeline:pipeline0/GstH265Parse:h265parse0.GstPad:src: caps = video/x-h265, width=(int)1920, height=(int)1080, framerate=(fraction)25/1, chroma-format=(string)4:2:0, bit-depth-luma=(uint)10, bit-depth-chroma=(uint)10, parsed=(boolean)true, stream-format=(string)hvc1, alignment=(string)au, pixel-aspect-ratio=(fraction)1/1, profile=(string)main-10, tier=(string)main, level=(string)4, codec_data=(buffer)01022000000090000000000078f000fcfdfafa00000f03200001001840010c01ffff022000000300900000030000030078350240210001002e420101022000000300900000030000030078a003c0801107cada35b91b4bffc0004000404000000300400000064222000100074401c064581120
[2023-05-05 02:02:55.096084] DEBUG: slash: /GstPipeline:pipeline0/GstVaapiDecode_h265:vaapidecode_h265-0.GstPad:sink: caps = video/x-h265, width=(int)1920, height=(int)1080, framerate=(fraction)25/1, chroma-format=(string)4:2:0, bit-depth-luma=(uint)10, bit-depth-chroma=(uint)10, parsed=(boolean)true, stream-format=(string)hvc1, alignment=(string)au, pixel-aspect-ratio=(fraction)1/1, profile=(string)main-10, tier=(string)main, level=(string)4, codec_data=(buffer)01022000000090000000000078f000fcfdfafa00000f03200001001840010c01ffff022000000300900000030000030078350240210001002e420101022000000300900000030000030078a003c0801107cada35b91b4bffc0004000404000000300400000064222000100074401c064581120
[2023-05-05 02:02:55.098986] DEBUG: slash: /GstPipeline:pipeline0/GstRawVideoParse:rawvideoparse0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, framerate=(fraction)25/1
[2023-05-05 02:02:55.099115] DEBUG: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert1.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, framerate=(fraction)25/1
[2023-05-05 02:02:55.099150] DEBUG: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter1.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, framerate=(fraction)25/1
[2023-05-05 02:02:55.099177] DEBUG: slash: /GstPipeline:pipeline0/GstFFMpegVidCmp:cmp.GstPad:sink_2: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, framerate=(fraction)25/1
[2023-05-05 02:02:55.099210] DEBUG: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter1.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, framerate=(fraction)25/1
[2023-05-05 02:02:55.099235] DEBUG: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert1.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)mpeg2, framerate=(fraction)25/1
[2023-05-05 02:02:55.099432] DEBUG: slash: Redistribute latency...
[2023-05-05 02:02:55.099483] DEBUG: slash: /GstPipeline:pipeline0/GstVaapiDecode_h265:vaapidecode_h265-0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099590] DEBUG: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099636] DEBUG: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099667] DEBUG: slash: /GstPipeline:pipeline0/GstFFMpegVidCmp:cmp.GstPad:src: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099727] DEBUG: slash: /GstPipeline:pipeline0/GstFakeSink:fakesink0.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099783] DEBUG: slash: /GstPipeline:pipeline0/GstFFMpegVidCmp:cmp.GstPad:sink_1: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099808] DEBUG: slash: /GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.099833] DEBUG: slash: /GstPipeline:pipeline0/GstVideoConvert:videoconvert0.GstPad:sink: caps = video/x-raw, format=(string)P010_10LE, width=(int)1920, height=(int)1080, interlace-mode=(string)progressive, multiview-mode=(string)mono, multiview-flags=(GstVideoMultiviewFlagsSet)0:ffffffff:/right-view-first/left-flipped/left-flopped/right-flipped/right-flopped/half-aspect/mixed-mono, pixel-aspect-ratio=(fraction)1/1, framerate=(fraction)25/1
[2023-05-05 02:02:55.157634] DEBUG: slash: Pipeline is PREROLLED ...
[2023-05-05 02:02:55.157746] DEBUG: slash: Setting pipeline to PLAYING ...
[2023-05-05 02:02:55.157786] DEBUG: slash: Redistribute latency...
[2023-05-05 02:02:55.157813] DEBUG: slash: New clock: GstSystemClock
[2023-05-05 02:02:56.648210] DEBUG: slash: Got EOS from element "pipeline0".
[2023-05-05 02:02:56.648345] DEBUG: slash: Execution ended after 0:00:01.490587303
[2023-05-05 02:02:56.648395] DEBUG: slash: Setting pipeline to NULL ...
[2023-05-05 02:02:56.649519] DEBUG: slash: Freeing pipeline ...
[2023-05-05 02:02:56.656712] INFO: slash: DETAIL: time(gst:decode:1) = 1.7272s
[2023-05-05 02:02:56.657107] INFO: slash: DETAIL: drv.iHD.psnr:expect = [36.3977, 41.5977, 41.0029, 36.8652, 42.0365, 41.5213]
[2023-05-05 02:02:56.657167] INFO: slash: DETAIL: drv.iHD.psnr:actual = [36.4, 21.73, 24.45, 36.8725, 21.8365, 24.6773]
```

**Comment by uartie** [comment]
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4546

**Comment by uartie** [comment]
@xhaihao regression fixed.  Checks pass.

**Comment by xhaihao** [comment]
> Video meta in allocation query was removed and caused the regression. Adding patch to this PR to fix it. I will send the fix to upstream tomorrow.

I'm curious why it can pass without video meta in allocation query on other platforms.

**Comment by HeJunyan** [comment]
> > Video meta in allocation query was removed and caused the regression. Adding patch to this PR to fix it. I will send the fix to upstream tomorrow.
> 
> I'm curious why it can pass without video meta in allocation query on other platforms.

Even without video meta, most of the time, the memory dump data is still correct if the resolutions are 4 aligned. For example, only 1023, 509, etc, this strange resolution will generate image garbage.

**Comment by xhaihao** [comment]
> > > Video meta in allocation query was removed and caused the regression. Adding patch to this PR to fix it. I will send the fix to upstream tomorrow.
> > 
> > 
> > I'm curious why it can pass without video meta in allocation query on other platforms.
> 
> Even without video meta, most of the time, the memory dump data is still correct if the resolutions are 4 aligned. For example, only 1023, 509, etc, this strange resolution will generate image garbage.

So does it imply we have different cases on CML and other platforms ? There are strange resolution on CML but not on other platforms ?

**Comment by xhaihao** [comment]
@HeJunyan According to [the info ](https://github.com/intel/cartwheel-gstreamer/pull/60#issuecomment-1535659499), the solution is 1920x1080 which is 4-byte aligned.

**Comment by HeJunyan** [comment]
This happens before. 

When dumping the image, the typical usage case is:
call gst_video_frame_map() first and call gst_video_frame_copy() to do the real image copy.

If not video meta provided, the _map will use the system default video info, while the video meta provide HW aligned video info.

What I am curious is that if this new ffmpeg plugin forgets to report VIDEO_META_API, the va plugins will already help to down image for it(If the va plugins find the the downstream element does not support VIDEO_META_API, it will download the surface to image and push CPU buffers to downstream).

**Pull request merged**
