### PR TITLE
msdk: Remove decoder refact patches

### PR DESCRIPTION
**Pull request by mengker33**

### CODE REVIEW

**Comment by uartie** [comment]
Remaining patches don't apply after removing these... please fix.

**Comment by uartie** [comment]
Also, in your commit message please justify why these are being removed... upstreamed?

**Comment by mengker33** [comment]
> Remaining patches don't apply after removing these... please fix.

@tong1wu, could you help to fix it? It looks like your patchset has conflicts, thanks.

**Comment by mengker33** [comment]
> Also, in your commit message please justify why these are being removed... upstreamed?

Yes, they are upstreamed.  Have updated the commit message. Thanks

**Comment by mengker33** [comment]
Wutong helped to remove msdkdec refact pacthset and fix conflicts in https://github.com/intel/cartwheel-gstreamer/pull/47. Close this one.

**Pull request closed without merging**
